### ISSUE TITLE
Failed to activate the all-times-you-know package

### ISSUE THREAD

**Issue by cakiem8x** [thenewvu/atom-all-times-you-know#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [all-times-you-know](https://github.com/thenewvu/atom-all-times-you-know) package, v0.6.1
### Stack Trace

Failed to activate the all-times-you-know package

```
At url.format is not a function

TypeError: url.format is not a function
  at AllTimesYouKnowView.refresh (/Users/bi/.atom/packages/all-times-you-know/lib/all-times-you-know-view.coffee:56:17)
  at AllTimesYouKnowView.refresh (/Users/bi/.atom/packages/all-times-you-know/lib/all-times-you-know-view.coffee:1:1)
  at new AllTimesYouKnowView (/Users/bi/.atom/packages/all-times-you-know/lib/all-times-you-know-view.coffee:21:6)
  at Object.module.exports.AllTimesYouKnow.activate (/Users/bi/.atom/packages/all-times-you-know/lib/all-times-you-know.coffee:37:32)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:389:60
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)

```
### Commands

```
     -3:33.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:52.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "activate-power-mode"
    ]
  },
  "all-times-you-know": {
    "size": "o",
    "tags": "nature"
  }
}
```
### Installed Packages

``` coffee
# User
all-times-you-know, v0.6.1
auto-indent, v0.5.0
autocomplete-json, v1.11.0
editorconfig, v1.4.1
javascript-snippets, v1.2.1
language-javascript-jsx, v0.3.7
minimap, v4.24.2
nuclide, v0.139.0
sync-settings, v0.7.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by thenewvu** [comment]
Close this because of [flickr-background](https://github.com/thenewvu/atom-flickr-background).
